name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hostinger
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: . # Path to your PHP project files
          remote-dir: /path/to/your/remote/directory
